# Generated by Django 3.2.6 on 2021-08-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='nome',
            new_name='sala',
        ),
    ]
