# Generated by Django 3.2.6 on 2021-08-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_rename_nome_sala_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(verbose_name='Inicio')),
                ('data_final', models.DateTimeField(verbose_name='Final')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.sala', verbose_name='Sala')),
            ],
        ),
    ]
