# Generated by Django 3.2.6 on 2021-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
    ]
