# Generated by Django 3.2.6 on 2021-09-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_sala_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='ordem',
            field=models.IntegerField(default=99, null=True, verbose_name='Ordem'),
        ),
    ]
