# Generated by Django 3.2.6 on 2024-04-21 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_sala_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.sala', verbose_name='Sala'),
        ),
    ]
